# Generated by Django 3.1.6 on 2021-02-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210205_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='owner',
        ),
    ]
